name: Web Scraper CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -R

    - name: Run tests with pytest
      run: |
        pytest test/